// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef lab11_h
#define lab11_h
#include <FL/Fl.H>
#include <string.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_PNG_Image.H>
extern Fl_Double_Window *start_win;
#include <FL/Fl_Box.H>
#include <FL/Fl_JPEG_Image.H>
#include <FL/Fl_Button.H>
extern Fl_Button *start;
#include <FL/Fl_Text_Display.H>
void background_timer(void*);
void load_images();
void cb_sky(void*);
extern Fl_Double_Window *win;
extern Fl_Box *sky;
extern Fl_Box *catch_window;
extern Fl_Button *button;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *life;
extern Fl_Value_Output *score;
void show_window();
extern Fl_Double_Window *gameover;
#include<FL/Fl_JPEG_Image.h>
extern Fl_Value_Output *yourscore;
extern Fl_Value_Output *higherscore;
void end_window();
#endif
